apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: timeappv1
spec:
  parentRefs:
  - name: gateway
  hostnames:
  - timehost
  - localhost
  rules:
  - backendRefs:
    - name: timeappv1
      port: 8000
      weight: 50 
    - name: timeappv2
      port: 8000
      weight: 50